### ISSUE TITLE
Get hi resolution image after camera capture

### ISSUE THREAD

**Issue by yogeshpaliyal** [hi-manshu/Pluck#5]
By using this, this will only return the thumbnail of the image.
Please add a option to get full file or uri.

https://github.com/hi-manshu/Pluck/blob/86976a09c75804987e1abc9853469f360e2e66b1/pluck/src/main/java/com/himanshoe/pluck/ui/Pluck.kt#L87

**Comment by hi-manshu** [comment]
Yea that is something, which will be improved with time. It was just to get started!

**Comment by hi-manshu** [comment]
Updated it @yogeshpaliyal . Thanks for inputs!
